export default [
  {
      "id": 1,
      "name": "防御1",
      "attribute": "地",
      "earth": 1,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "DEF+5%",
      "effect": ""
  },
  {
      "id": 2,
      "name": "防御2",
      "attribute": "地",
      "earth": 2,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "DEF+10%",
      "effect": ""
  },
  {
      "id": 3,
      "name": "防御3",
      "attribute": "地",
      "earth": 3,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "DEF+15%",
      "effect": ""
  },
  {
      "id": 4,
      "name": "防御3+",
      "attribute": "地",
      "earth": 3,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "DEF+20%",
      "effect": ""
  },
  {
      "id": 5,
      "name": "破坏1",
      "attribute": "地",
      "earth": 1,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+10",
      "effect": "造成晕眩值+15%"
  },
  {
      "id": 6,
      "name": "破坏2",
      "attribute": "地",
      "earth": 2,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+20",
      "effect": "造成晕眩值+20%"
  },
  {
      "id": 7,
      "name": "破坏3",
      "attribute": "地",
      "earth": 3,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+30",
      "effect": "造成晕眩值+25%"
  },
  {
      "id": 8,
      "name": "破坏3+",
      "attribute": "地",
      "earth": 3,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+50",
      "effect": "造成晕眩值+30%"
  },
  {
      "id": 9,
      "name": "毒之刃",
      "attribute": "地",
      "earth": 1,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有15%概率附加中毒"
  },
  {
      "id": 10,
      "name": "石化之刃",
      "attribute": "地",
      "earth": 2,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有10%概率附加石化"
  },
  {
      "id": 11,
      "name": "黄玉之盾",
      "attribute": "地",
      "earth": 2,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 2,
      "bonus": "",
      "effect": "危机时4回合DEF·ADF↑"
  },
  {
      "id": 12,
      "name": "耀脉",
      "attribute": "地",
      "earth": 3,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "装备者以指令战斗打倒敌人时获得的耀晶石量+30%"
  },
  {
      "id": 13,
      "name": "精神1",
      "attribute": "水",
      "earth": 0,
      "water": 1,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "ATS+5%",
      "effect": ""
  },
  {
      "id": 14,
      "name": "精神2",
      "attribute": "水",
      "earth": 0,
      "water": 2,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "ATS+10%",
      "effect": ""
  },
  {
      "id": 15,
      "name": "精神3",
      "attribute": "水",
      "earth": 0,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "ATS+15%",
      "effect": ""
  },
  {
      "id": 16,
      "name": "精神3+",
      "attribute": "水",
      "earth": 0,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "ATS+20%",
      "effect": ""
  },
  {
      "id": 17,
      "name": "HP1",
      "attribute": "水",
      "earth": 0,
      "water": 1,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "HP上限提升10%"
  },
  {
      "id": 18,
      "name": "HP2",
      "attribute": "水",
      "earth": 0,
      "water": 2,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "HP上限提升20%"
  },
  {
      "id": 19,
      "name": "HP3",
      "attribute": "水",
      "earth": 0,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "HP上限提升30%"
  },
  {
      "id": 20,
      "name": "HP3+",
      "attribute": "水",
      "earth": 0,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "HP上限提升40%"
  },
  {
      "id": 21,
      "name": "冻结之刃",
      "attribute": "水",
      "earth": 0,
      "water": 2,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有10%概率附加冻结"
  },
  {
      "id": 22,
      "name": "苍玉之盾",
      "attribute": "水",
      "earth": 0,
      "water": 2,
      "fire": 2,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "危机时4回合“逐渐回复HP”"
  },
  {
      "id": 23,
      "name": "治愈",
      "attribute": "水",
      "earth": 0,
      "water": 2,
      "fire": 0,
      "wind": 2,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "在原野中逐渐回复HP"
  },
  {
      "id": 24,
      "name": "慈爱",
      "attribute": "水",
      "earth": 3,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "回复魔法的效果+30%"
  },
  {
      "id": 25,
      "name": "攻击1",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 1,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+5%、DEF-5%",
      "effect": ""
  },
  {
      "id": 26,
      "name": "攻击2",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 2,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+10%、DEF-10%",
      "effect": ""
  },
  {
      "id": 27,
      "name": "攻击3",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+15%、DEF-15%",
      "effect": ""
  },
  {
      "id": 28,
      "name": "攻击3+",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+20%、DEF-20%",
      "effect": ""
  },
  {
      "id": 29,
      "name": "必杀1",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 1,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "必杀率+3%",
      "effect": ""
  },
  {
      "id": 30,
      "name": "必杀2",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 2,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "必杀率+6%",
      "effect": ""
  },
  {
      "id": 31,
      "name": "必杀3",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "必杀率+9%",
      "effect": ""
  },
  {
      "id": 32,
      "name": "必杀3+",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+7 必杀率+10%",
      "effect": ""
  },
  {
      "id": 33,
      "name": "炎伤之刃",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 1,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有15%概率附加炎伤"
  },
  {
      "id": 34,
      "name": "封技之刃",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 2,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有15%概率附加封技"
  },
  {
      "id": 35,
      "name": "红玉之盾",
      "attribute": "火",
      "earth": 2,
      "water": 0,
      "fire": 2,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "危机时4回合STR↑"
  },
  {
      "id": 36,
      "name": "机功",
      "attribute": "火",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "在原野中逐渐回复EP"
  },
  {
      "id": 37,
      "name": "魔防1",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 1,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "魔法回避率+3%、ADF+5%",
      "effect": ""
  },
  {
      "id": 38,
      "name": "魔防2",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 2,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "魔法回避率+6%、ADF+10%",
      "effect": ""
  },
  {
      "id": 39,
      "name": "魔防3",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "魔法回避率+9%、ADF+15%",
      "effect": ""
  },
  {
      "id": 40,
      "name": "魔防3+",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+7 魔法回避率+10%、ADF+20%",
      "effect": ""
  },
  {
      "id": 41,
      "name": "回避1",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 1,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "回避率+3%",
      "effect": ""
  },
  {
      "id": 42,
      "name": "回避2",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 2,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "回避率+6%",
      "effect": ""
  },
  {
      "id": 43,
      "name": "回避3",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "回避率+9%",
      "effect": ""
  },
  {
      "id": 44,
      "name": "回避3+",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+7 回避率+10%",
      "effect": ""
  },
  {
      "id": 45,
      "name": "睡眠之刃",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 2,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有15%概率附加睡眠"
  },
  {
      "id": 46,
      "name": "翠玉之盾",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 2,
      "time": 0,
      "space": 2,
      "illusion": 0,
      "bonus": "",
      "effect": "危机时2回合心眼"
  },
  {
      "id": 47,
      "name": "异香",
      "attribute": "风",
      "earth": 3,
      "water": 3,
      "fire": 3,
      "wind": 3,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "在原野及指令战斗中，更容易被敌人锁定"
  },
  {
      "id": 48,
      "name": "暴威",
      "attribute": "风",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 3,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "",
      "effect": "剩余HP越少，造成的魔法伤害越高（最高200%）"
  },
  {
      "id": 49,
      "name": "行动力1",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 1,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+10%",
      "effect": ""
  },
  {
      "id": 50,
      "name": "行动力2",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 2,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+20%",
      "effect": ""
  },
  {
      "id": 51,
      "name": "行动力3",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+30%",
      "effect": ""
  },
  {
      "id": 52,
      "name": "行动力3+",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+40%",
      "effect": ""
  },
  {
      "id": 53,
      "name": "驱动1",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 1,
      "space": 1,
      "illusion": 0,
      "bonus": "ATS+10",
      "effect": "魔法驱动时间0.7倍"
  },
  {
      "id": 54,
      "name": "驱动2",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 2,
      "space": 2,
      "illusion": 1,
      "bonus": "ATS+20",
      "effect": "魔法驱动时间0.5倍"
  },
  {
      "id": 55,
      "name": "驱动3",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 3,
      "illusion": 2,
      "bonus": "ATS+30",
      "effect": "魔法驱动时间0.3倍"
  },
  {
      "id": 56,
      "name": "驱动3+",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 3,
      "illusion": 2,
      "bonus": "ATS+50",
      "effect": "魔法驱动时间0.2倍"
  },
  {
      "id": 57,
      "name": "暗之刃",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 1,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "普通攻击·战技有15%概率附加黑暗"
  },
  {
      "id": 58,
      "name": "灭之刃",
      "attribute": "时",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 0,
      "illusion": 0,
      "bonus": "STR+25",
      "effect": "普通攻击·战技有10%概率附加即死"
  },
  {
      "id": 59,
      "name": "暗玉之盾",
      "attribute": "时",
      "earth": 0,
      "water": 3,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 0,
      "illusion": 0,
      "bonus": "",
      "effect": "危机时4回合SPD·MOV↑"
  },
  {
      "id": 60,
      "name": "豪运",
      "attribute": "时",
      "earth": 5,
      "water": 0,
      "fire": 0,
      "wind": 5,
      "time": 0,
      "space": 0,
      "illusion": 0,
      "bonus": "SPD+7",
      "effect": "装备者以指令战斗打倒敌人时道具掉落率+50%"
  },
  {
      "id": 61,
      "name": "命中1",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 1,
      "illusion": 0,
      "bonus": "STR+10 命中率+60%",
      "effect": ""
  },
  {
      "id": 62,
      "name": "命中2",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 2,
      "illusion": 0,
      "bonus": "STR+20 命中率+80%",
      "effect": ""
  },
  {
      "id": 63,
      "name": "命中3",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "STR+30 命中率+100%",
      "effect": ""
  },
  {
      "id": 64,
      "name": "命中3+",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "STR+50 命中率+150%",
      "effect": ""
  },
  {
      "id": 65,
      "name": "省EP1",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 1,
      "space": 1,
      "illusion": 0,
      "bonus": "",
      "effect": "消耗EP变为0.4倍"
  },
  {
      "id": 66,
      "name": "省EP2",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 2,
      "space": 2,
      "illusion": 1,
      "bonus": "",
      "effect": "消耗EP变为0.3倍"
  },
  {
      "id": 67,
      "name": "省EP3",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 3,
      "illusion": 2,
      "bonus": "",
      "effect": "消耗EP变为0.2倍"
  },
  {
      "id": 68,
      "name": "省EP3+",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 3,
      "illusion": 2,
      "bonus": "",
      "effect": "消耗EP变为0.1倍"
  },
  {
      "id": 69,
      "name": "封魔之刃",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "STR+25",
      "effect": "普通攻击·战技有30%概率附加封魔"
  },
  {
      "id": 70,
      "name": "黄金之盾",
      "attribute": "空",
      "earth": 3,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "DEF·ADF+50",
      "effect": "危机时4回合逐渐回复CP"
  },
  {
      "id": 71,
      "name": "天启",
      "attribute": "空",
      "earth": 0,
      "water": 5,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 5,
      "illusion": 0,
      "bonus": "",
      "effect": "范围魔法效果范围+5m"
  },
  {
      "id": 72,
      "name": "孤剑",
      "attribute": "空",
      "earth": 0,
      "water": 0,
      "fire": 5,
      "wind": 0,
      "time": 0,
      "space": 5,
      "illusion": 0,
      "bonus": "",
      "effect": "剩余HP越少，造成的物理伤害越高（最高200%）"
  },
  {
      "id": 73,
      "name": "妨碍1",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 1,
      "bonus": "",
      "effect": "攻击时有30%概率触发解除驱动/延迟极小"
  },
  {
      "id": 74,
      "name": "妨碍2",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 2,
      "bonus": "",
      "effect": "攻击时有60%概率触发解除驱动/延迟极小"
  },
  {
      "id": 75,
      "name": "妨碍3",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 3,
      "bonus": "",
      "effect": "攻击时有90%概率触发解除驱动/延迟极小"
  },
  {
      "id": 76,
      "name": "妨碍3+",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 0,
      "illusion": 3,
      "bonus": "STR+50",
      "effect": "攻击时有100%概率触发解除驱动/延迟极小"
  },
  {
      "id": 77,
      "name": "EP1",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 1,
      "illusion": 1,
      "bonus": "EP上限提升20%",
      "effect": ""
  },
  {
      "id": 78,
      "name": "EP2",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 1,
      "space": 2,
      "illusion": 2,
      "bonus": "EP上限提升35%",
      "effect": ""
  },
  {
      "id": 79,
      "name": "EP3",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 2,
      "space": 3,
      "illusion": 3,
      "bonus": "EP上限提升50%",
      "effect": ""
  },
  {
      "id": 80,
      "name": "EP3+",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 2,
      "space": 3,
      "illusion": 3,
      "bonus": "EP上限提升65%",
      "effect": ""
  },
  {
      "id": 81,
      "name": "混沌之刃",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "STR+25",
      "effect": "普通攻击·战技有15%概率附加混乱"
  },
  {
      "id": 82,
      "name": "白银之盾",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 3,
      "wind": 0,
      "time": 0,
      "space": 3,
      "illusion": 0,
      "bonus": "DEF·ADF+50",
      "effect": "危机时4回合ATS↑"
  },
  {
      "id": 83,
      "name": "阳炎",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 0,
      "time": 3,
      "space": 3,
      "illusion": 3,
      "bonus": "",
      "effect": "在原野及指令战斗中，不易成为敌人的目标"
  },
  {
      "id": 84,
      "name": "叶隐",
      "attribute": "幻",
      "earth": 0,
      "water": 0,
      "fire": 0,
      "wind": 5,
      "time": 0,
      "space": 0,
      "illusion": 5,
      "bonus": "命中率+100%、必杀率+10%、回避率·魔法回避率+25%",
      "effect": ""
  }
]