export default [
  {
    "name": "石之锤",
    "attribute": "地",
    "earth": 1,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 10,
    "type": "魔法",
    "damage": "C+",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "石化10%"
  },
  {
    "name": "大地之枪",
    "attribute": "地",
    "earth": 2,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 30,
    "type": "魔法",
    "damage": "C+",
    "target": "敌方",
    "range": "扇形",
    "rangeAppend": "M",
    "effect": "石化20%"
  },
  {
    "name": "石化吐息",
    "attribute": "地",
    "earth": 3,
    "water": 0,
    "fire": 0,
    "wind": 2,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 60,
    "type": "魔法",
    "damage": "B",
    "target": "敌方",
    "range": "扇形",
    "rangeAppend": "L",
    "effect": "中毒·石化30%"
  },
  {
    "name": "陨石冲击",
    "attribute": "地",
    "earth": 4,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 120,
    "type": "魔法",
    "damage": "A",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "M",
    "effect": "晕眩·大"
  },
  {
    "name": "泰坦之咆哮",
    "attribute": "地",
    "earth": 5,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 3,
    "illusion": 0,
    "ep_cost": 300,
    "type": "魔法",
    "damage": "S",
    "target": "敌方",
    "range": "全体",
    "rangeAppend": "",
    "effect": "DEF↓"
  },
  {
    "name": "大地防护",
    "attribute": "地",
    "earth": 2,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 2,
    "ep_cost": 60,
    "type": "辅助",
    "damage": "—",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "L",
    "effect": "护盾小"
  },
  {
    "name": "大地之墙",
    "attribute": "地",
    "earth": 4,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 3,
    "illusion": 0,
    "ep_cost": 240,
    "type": "辅助",
    "damage": "—",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "L",
    "effect": "完全防御"
  },
  {
    "name": "结晶防护",
    "attribute": "地",
    "earth": 1,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 1,
    "ep_cost": 30,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "5回合DEF↑/逐渐回复HP/解除能力降低"
  },
  {
    "name": "高压水块",
    "attribute": "水",
    "earth": 0,
    "water": 1,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 10,
    "type": "魔法",
    "damage": "C+",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "封魔30%"
  },
  {
    "name": "水蓝冲击",
    "attribute": "水",
    "earth": 0,
    "water": 3,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 120,
    "type": "魔法",
    "damage": "A+",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "S",
    "effect": "封魔60%"
  },
  {
    "name": "钻石星尘",
    "attribute": "水",
    "earth": 0,
    "water": 5,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 5,
    "illusion": 0,
    "ep_cost": 300,
    "type": "魔法",
    "damage": "S+",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "M",
    "effect": "冻结40%"
  },
  {
    "name": "回复术",
    "attribute": "水",
    "earth": 0,
    "water": 1,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 10,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "回复HP小"
  },
  {
    "name": "中回复术",
    "attribute": "水",
    "earth": 0,
    "water": 3,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 30,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "回复HP中"
  },
  {
    "name": "大回复术",
    "attribute": "水",
    "earth": 0,
    "water": 5,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 60,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "回复HP大"
  },
  {
    "name": "回复术·复",
    "attribute": "水",
    "earth": 0,
    "water": 2,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 2,
    "illusion": 0,
    "ep_cost": 40,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "圆",
    "rangeAppend": "L",
    "effect": "回复HP小"
  },
  {
    "name": "中回复术·复",
    "attribute": "水",
    "earth": 0,
    "water": 4,
    "fire": 0,
    "wind": 2,
    "time": 0,
    "space": 2,
    "illusion": 0,
    "ep_cost": 100,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "圆",
    "rangeAppend": "LL",
    "effect": "回复HP中"
  },
  {
    "name": "治愈术",
    "attribute": "水",
    "earth": 0,
    "water": 1,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 1,
    "ep_cost": 10,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "HP回复10%/解除减益"
  },
  {
    "name": "治愈术·复",
    "attribute": "水",
    "earth": 0,
    "water": 3,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 2,
    "ep_cost": 30,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "圆",
    "rangeAppend": "LL",
    "effect": "HP回复20%/解除减益"
  },
  {
    "name": "复苏术",
    "attribute": "水",
    "earth": 0,
    "water": 4,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 2,
    "illusion": 0,
    "ep_cost": 30,
    "type": "回复",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "复活/回复HP小"
  },
  {
    "name": "火焰箭",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 1,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 10,
    "type": "魔法",
    "damage": "C+",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "炎伤20%"
  },
  {
    "name": "烈火箭",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 2,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 60,
    "type": "魔法",
    "damage": "B",
    "target": "敌方",
    "range": "直线",
    "rangeAppend": "S",
    "effect": "炎伤30%"
  },
  {
    "name": "燃烧之息",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 3,
    "wind": 2,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 120,
    "type": "魔法",
    "damage": "A",
    "target": "敌方",
    "range": "圆",
    "rangeAppend": "M",
    "effect": "炎伤40%"
  },
  {
    "name": "火焰箭·改",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 4,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 240,
    "type": "魔法",
    "damage": "S",
    "target": "敌方",
    "range": "圆",
    "rangeAppend": "S",
    "effect": "炎伤50%"
  },
  {
    "name": "螺旋之炎",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 5,
    "wind": 2,
    "time": 0,
    "space": 4,
    "illusion": 0,
    "ep_cost": 330,
    "type": "魔法",
    "damage": "S+",
    "target": "敌方",
    "range": "圆",
    "rangeAppend": "L",
    "effect": "炎伤60%"
  },
  {
    "name": "火山之咆哮",
    "attribute": "火",
    "earth": 3,
    "water": 0,
    "fire": 5,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 5,
    "ep_cost": 360,
    "type": "魔法",
    "damage": "SS",
    "target": "敌方",
    "range": "圆",
    "rangeAppend": "S",
    "effect": "炎伤90%"
  },
  {
    "name": "强音之力",
    "attribute": "火",
    "earth": 0,
    "water": 0,
    "fire": 1,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 1,
    "ep_cost": 30,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "5回合STR↑/CP逐渐上升/解除能力降低"
  },
  {
    "name": "风之轮",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 1,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 10,
    "type": "魔法",
    "damage": "C+",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "黑暗20%"
  },
  {
    "name": "风之领域",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 3,
    "time": 0,
    "space": 0,
    "illusion": 0,
    "ep_cost": 90,
    "type": "魔法",
    "damage": "B",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "L",
    "effect": "黑暗40%"
  },
  {
    "name": "狂怒风暴",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 4,
    "time": 2,
    "space": 0,
    "illusion": 2,
    "ep_cost": 240,
    "type": "魔法",
    "damage": "S",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "LL",
    "effect": "黑暗60%"
  },
  {
    "name": "雷光",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 3,
    "time": 0,
    "space": 2,
    "illusion": 0,
    "ep_cost": 120,
    "type": "魔法",
    "damage": "A",
    "target": "敌方",
    "range": "直线",
    "rangeAppend": "S",
    "effect": "封技20%"
  },
  {
    "name": "电浆波动",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 3,
    "wind": 5,
    "time": 0,
    "space": 5,
    "illusion": 0,
    "ep_cost": 300,
    "type": "魔法",
    "damage": "S+",
    "target": "敌方",
    "range": "直线",
    "rangeAppend": "M",
    "effect": "封技40%"
  },
  {
    "name": "风之防壁",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 2,
    "time": 0,
    "space": 0,
    "illusion": 2,
    "ep_cost": 60,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "免疫减益效果/5回合ADF↑/解除能力降低"
  },
  {
    "name": "风之翼击",
    "attribute": "风",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 4,
    "time": 0,
    "space": 0,
    "illusion": 4,
    "ep_cost": 240,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "全体",
    "rangeAppend": "",
    "effect": "5回合ATS↑/5回合心眼/解除能力降低"
  },
  {
    "name": "心灵之霞",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 1,
    "space": 0,
    "illusion": 0,
    "ep_cost": 20,
    "type": "魔法",
    "damage": "B",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "晕眩·大"
  },
  {
    "name": "暗影之矛",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 2,
    "space": 0,
    "illusion": 0,
    "ep_cost": 60,
    "type": "魔法",
    "damage": "A",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "即死10%"
  },
  {
    "name": "地狱之门",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 2,
    "wind": 0,
    "time": 3,
    "space": 2,
    "illusion": 0,
    "ep_cost": 120,
    "type": "魔法",
    "damage": "A+",
    "target": "敌方",
    "range": "扇形",
    "rangeAppend": "L",
    "effect": "中毒90%"
  },
  {
    "name": "苍白地狱",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 5,
    "space": 0,
    "illusion": 5,
    "ep_cost": 240,
    "type": "魔法",
    "damage": "S",
    "target": "地点",
    "range": "圆",
    "rangeAppend": "M",
    "effect": "黑暗30%/STR↓"
  },
  {
    "name": "时间加速",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 1,
    "space": 1,
    "illusion": 0,
    "ep_cost": 10,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "5回合SPD·MOV↑/解除能力降低"
  },
  {
    "name": "时间加速改",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 3,
    "space": 3,
    "illusion": 0,
    "ep_cost": 240,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "加速/5回合SPD·MOV↑↑/解除能力降低"
  },
  {
    "name": "魔力封锁",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 2,
    "space": 0,
    "illusion": 2,
    "ep_cost": 120,
    "type": "妨碍",
    "damage": "—",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "解除驱动/封魔200%/消除增益"
  },
  {
    "name": "全面魔力封锁",
    "attribute": "时",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 3,
    "space": 0,
    "illusion": 3,
    "ep_cost": 240,
    "type": "妨碍",
    "damage": "—",
    "target": "敌方",
    "range": "全体",
    "rangeAppend": "",
    "effect": "解除驱动/封魔200%/消除增益"
  },
  {
    "name": "神圣祝福",
    "attribute": "幻",
    "earth": 0,
    "water": 1,
    "fire": 0,
    "wind": 1,
    "time": 0,
    "space": 1,
    "illusion": 2,
    "ep_cost": 60,
    "type": "辅助",
    "damage": "—",
    "target": "我方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "5回合所有能力↑/解除能力降低"
  },
  {
    "name": "混沌利刃",
    "attribute": "幻",
    "earth": 0,
    "water": 0,
    "fire": 0,
    "wind": 0,
    "time": 0,
    "space": 0,
    "illusion": 3,
    "ep_cost": 60,
    "type": "妨碍",
    "damage": "—",
    "target": "敌方",
    "range": "单体",
    "rangeAppend": "",
    "effect": "混乱·中毒90%/DEF·ADF·SPD↓↓"
  }
]